name: Reproduce classpath snapshot issue
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build package With 0.0.7 version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: source:compileKotlin -i
      - name: Upload 0.0.7 artifact
        uses: actions/upload-artifact@v3
        with:
          name: 0.0.7-artifact
          path: source/build/classes/kotlin/main/org/example/DefaultParameterInvoke.class
      - name: Sed with 0.0.8 version
        run: |
          sed -i 's/0.0.7/0.0.8/g' ./source/build.gradle.kts
      - name: Build package With 0.0.8 version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: source:compileKotlin -i
      - name: Upload 0.0.8 artifact
        uses: actions/upload-artifact@v3
        with:
          name: 0.0.8-artifact
          path: source/build/classes/kotlin/main/org/example/DefaultParameterInvoke.class